### ISSUE TITLE
trobules with z_ofset_calibration.py

### ISSUE THREAD

**Issue by real-alphamaennchen** [Rappetor/Sovol-SV08-Mainline#40]
Hi,
many thanks four your great work on bringing mainline klipper to SV08!
I am struggling with the z_offset_calibration.py. Here the traceback of the klippy.log:

Config error
Traceback (most recent call last):
  File "/home/biqu/klipper/klippy/klippy.py", line 130, in _connect
    self._read_config()
  File "/home/biqu/klipper/klippy/klippy.py", line 123, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/biqu/klipper/klippy/klippy.py", line 112, in load_object
    self.objects[section] = init_func(config.getsection(section))
  File "/home/biqu/klipper/klippy/extras/z_offset_calibration.py", line 123, in load_config
    return ZoffsetCalibration(config)
  File "/home/biqu/klipper/klippy/extras/z_offset_calibration.py", line 19, in __init__
    self.offsetadjust = float(self.read_varibles_cfg_value("offsetadjust"))
  File "/home/biqu/klipper/klippy/extras/z_offset_calibration.py", line 44, in read_varibles_cfg_value
    _value = _config.get('Variables', option)
  File "/usr/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.9/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Variables'

As i could see the original z_offset_calibration.py was reading from the "sovol" user folder (in line 43), so i changed that to the "biqu", but the same error occurred.

Du you have any ideas what I did wrong?

**Comment by real-alphamaennchen** [comment]
I am so stupid, I copied the wrong file!!!!
