### ISSUE TITLE
Flashing Klipper to BTT EDDY MCU ERROR

### ISSUE THREAD

**Issue by maj0r1337** [Rappetor/Sovol-SV08-Mainline#75]
hi Richard,

i recive the following error when i try to flash/update eddy usb.

```
Flashing Klipper to BTT EDDY MCU.

Entering bootloader on /dev/serial/by-id/usb-Klipper_rp2040_5044340310771C1C-if00
Flashing Serial Device /dev/serial/by-id/usb-katapult_rp2040_5044340310771C1C-if00, baud 250000
ERROR:root:Flash Error
Traceback (most recent call last):
  File "/home/biqu/katapult/scripts/flashtool.py", line 678, in main
    await sock.run(args.device, args.baud, fpath)
  File "/home/biqu/katapult/scripts/flashtool.py", line 610, in run
    raise FlashError("Invalid firmware path '%s'" % (fw_path))
FlashError: Invalid firmware path '/home/biqu/klipper/eddy_mcu_klipper.bin'

BTT EDDY MCU flashed. Check for errors and press [Enter] to continue..
```

best regards
Werner

**Comment by maj0r1337** [comment]
thank you, i installed the firmware like its purposed in the btt repo. i will install katapult on it and try again.

i will give it a try and report back

**Comment by maj0r1337** [comment]
of course you were right!!! thank you so much for your work!!!
