### ISSUE TITLE
Klipper install: `Unknown config object 'gcode_move'` in python script

### ISSUE THREAD

**Issue by heinrichWeichert** [Rappetor/Sovol-SV08-Mainline#89]
Using klipper HEAD (today), the python script (python3 3.9.2) exits with an error.
```
Config error
Traceback (most recent call last):
  File "/home/biqu/klipper/klippy/klippy.py", line 130, in _connect
    self._read_config()
  File "/home/biqu/klipper/klippy/klippy.py", line 123, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/biqu/klipper/klippy/klippy.py", line 112, in load_object
    self.objects[section] = init_func(config.getsection(section))
  File "/home/biqu/klipper/klippy/extras/z_offset_calibration.py", line 136, in load_config
    return ZoffsetCalibration(config)
  File "/home/biqu/klipper/klippy/extras/z_offset_calibration.py", line 21, in __init__
    self.gcode_move = self.printer.lookup_object('gcode_move')
  File "/home/biqu/klipper/klippy/klippy.py", line 79, in lookup_object
    raise self.config_error("Unknown config object '%s'" % (name,))
configparser.Error: Unknown config object 'gcode_move'
```

**Comment by heinrichWeichert** [comment]
My mistake, I forgot to add mainsail.cfg to the includes, this seems to force an implicit load of the missing module
